config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def show; end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit; end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article saved successfully!"
      redirect_to @article
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private
  def article_params
    params.require(:article).permit(:title, :description)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article do |form| %>
  <div class="mb-3">
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, class: "form-control" %>
    <% @article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
    <% @article.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= form.submit class: 'btn btn-lg btn-success' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1>Articles listing page</h1>

<table class="table">
  <thead>
  <tr>
    <th scope="col">Title</th>
    <th scope="col">Description</th>
    <th scope="col">Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.description %></td>
      <td>
        <%= link_to 'Show', article_path(article), type:"button", class:"btn btn-info" %>
      </td>
      <td>
        <%= link_to 'Edit', edit_article_path(article), type:"button", class:"btn btn-primary" %>
      </td>
      <td>
        <%= button_to 'Delete', article_path(article), method: :delete, type:"button", class:"btn btn-danger" %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1>Show article details</h1>

<h2>Title: <%= @article.id %></h2>

<p>Description: <%= @article.description %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
</head>

<body>
<div class="container">
  <% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>

  <% if flash[:alert] %>
    <div class="alert alert-success" role="alert">
      <%= alert %>
    </div>
  <% end %>

  <%= yield %>
</div>
</body>
</html>